### ISSUE TITLE
Linking issue with Intel oneAPI compiler on Cosma

### ISSUE THREAD

**Issue by tkoskela** [ukri-excalibur/excalibur-tests#155]
I'm getting a linker error when building sphng with spack on cosma
```
  >> 179    ld: /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/bin/intel64/../../bin/intel64/../../lib/icx-lto.so: error loading plugin: libimf.so: cannot open shared object file: No such file or directory
```
The strange thing is, when I look at that library it is linked to the correct path of libimf.so
```
$ ldd /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/bin/intel64/../../bin/intel64/../../lib/icx-lto.so
	linux-vdso.so.1 =>  (0x00007ffe89089000)
	librt.so.1 => /lib64/librt.so.1 (0x00002affdbca6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002affdbeae000)
	libimf.so => /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libimf.so (0x00002affdc0b2000)
	libm.so.6 => /lib64/libm.so.6 (0x00002affdc4aa000)
	libz.so.1 => /lib64/libz.so.1 (0x00002affdc7ac000)
	libsvml.so => /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libsvml.so (0x00002affdc9c2000)
	libirng.so => /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libirng.so (0x00002affddfd3000)
	libgcc_s.so.1 => /cosma/local/gcc/7.3.0/lib64/libgcc_s.so.1 (0x00002affde33d000)
	libintlc.so.5 => /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00002affd85be000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002affde554000)
	libc.so.6 => /lib64/libc.so.6 (0x00002affde770000)
	/lib64/ld-linux-x86-64.so.2 (0x00002affd8572000)
```
and it is where it's supposed to be
```
$ ls /cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libimf.so
/cosma/local/intel/oneAPI_2022.3.0/compiler/2022.2.1/linux/compiler/lib/intel64_lin/libimf.so
```

**Comment by giordano** [comment]
Never trust `ldd` blindly, it's a dumb tool.  Use [`libtree`](https://github.com/haampie/libtree) to see _why_ a library is found.  If that comes from `LD_LIBRARY_PATH` instead of RPATH/RUNPATH, that may explain why the linker can't find it.

**Comment by tkoskela** [comment]
`command not found` :unamused:

**Comment by tkoskela** [comment]
Ah, right, `ldd` only finds `libimf.so` when the `oneAPI` module is loaded. So I assume our spack environment is missing some paths

**Comment by giordano** [comment]
> command not found unamused

Yeah, I doubt any system is shipping it, but [I linked the repository for a reason
](https://github.com/haampie/libtree/blob/eb56287c1b4eb3b267524ab1e6e31f042b713395/README.md#building-from-sources)

> Or use the following unsafe quick install instructions
> ```
> curl -Lfs https://raw.githubusercontent.com/haampie/libtree/master/libtree.c | ${CC:-cc} -o libtree -x c - -std=c99 -D_FILE_OFFSET_BITS=64
> ``` 

> So I assume our spack environment is missing some paths 

It's more likely that you need to load the module when using the compiler, if that sets some special environment variables, for example like https://github.com/ukri-excalibur/excalibur-tests/blob/4380722d0233438a615e0d64837339970546e712/benchmarks/spack/archer2/compute-node/spack.yaml#L187-L189
