### ISSUE TITLE
Make excalibur-tests pip installable?

### ISSUE THREAD

**Issue by t-young31** [ukri-excalibur/excalibur-tests#17]
Currently the setup is a little involved and could perhaps be made simpler by making a setup script, either a setup.py in the root directory to make the whole repo pip installable or maybe a shell script that would:

- install python dependencies
- ~modify your bash_profile with the SPACK_ROOT~ not needed: https://github.com/eth-cscs/reframe/pull/2123
- copy the correct reframe config to ~/.reframe/settings.py 
- install all the extra [python modules](https://github.com/ukri-excalibur/excalibur-tests/tree/main/modules), so there wouldn't need to be any appending to sys.path (which relies on a consistent directory structure)
- prompt user to install spack, if it's not already present

**Comment by tkoskela** [comment]
Can we pip install [reframe](https://pypi.org/project/ReFrame-HPC/) as a dependency?

**Comment by giordano** [comment]
ReFrame yes: https://reframe-hpc.readthedocs.io/en/stable/started.html#pypi.  It's only Spack that can only be git-cloned.

**Comment by tkoskela** [comment]
The current version `4.0.2` in PyPi does not work for me. `3.11.0` is fine though

```
$ reframe --version
Traceback (most recent call last):
  File "/home/tkoskela/miniconda3/bin/reframe", line 19, in <module>
    import reframe.frontend.cli as cli  # noqa: F401, F403
  File "/home/tkoskela/miniconda3/lib/python3.8/site-packages/reframe/__init__.py", line 26, in <module>
    from reframe.core.decorators import *   # noqa: F401, F403
  File "/home/tkoskela/miniconda3/lib/python3.8/site-packages/reframe/core/decorators.py", line 22, in <module>
    from reframe.utility.versioning import VersionValidator
  File "/home/tkoskela/miniconda3/lib/python3.8/site-packages/reframe/utility/versioning.py", line 11, in <module>
    parse = semver.VersionInfo.parse
AttributeError: module 'semver' has no attribute 'VersionInfo'
```

**Comment by giordano** [comment]
Yes, at the moment we're stuck with version 3 (I mentioned it in Slack some time ago :slightly_smiling_face:)
