### ISSUE TITLE
Add data transformations in config and high-level script

### ISSUE THREAD

**Issue by ilectra** [ukri-excalibur/excalibur-tests#183]
In preparation for specific types of plots (especially scaling):
- allow `x_axis` or `y_axis` to be some transformation of the data, either between values of columns (eg. `tasks`/`num_CPUs`) or involving fixed values given in the config (eg. scaling by a fixed number). See if symPy can help with this.
- scale the y value for each series by a different number (eg. given in a dictionary). This is needed not only for scaling plots, eg. Babelstream benchmarks can be presented as scaled by the theoretical performance of each system.
- (largely moved to #194) scale y values by the value of the first point (usually the serial performance point in a scaling plot)

**Comment by pineapple-cat** [comment]
- Could add ability to normalise ratios. (Is there a use-case for this?)
- Zeros and missing values throw exceptions.
