### ISSUE TITLE
Implement UM structured mesh stencil in HPCG benchmark

### ISSUE THREAD

**Issue by tkoskela** [ukri-excalibur/excalibur-tests#225]
The current implementation(s) of the HPCG benchmark are in the [local spack repo](../blob/main/benchmarks/spack/repo/packages/hpcg_excalibur). They were added in https://github.com/ukri-excalibur/excalibur-tests/pull/157 The three implementations there are
- `hpcg_original`: Standard HPCG benchmark solving Poisson's equation in 3D with a 27pt stencil using CSR sparse matrix
- `hpcg_stencil`: Modified matrix-free implementation of HPCG benchmark solving Poisson's equation in 3D with a hard-coded 27pt stencil
- `hpcg_lfric`: Modified (?) implementation of HPCG benchmark solving a different problem with an [LFric](https://www.metoffice.gov.uk/research/approach/modelling-systems/lfric) stencil.

TODO: Add references/code for UM stencil to be added

**Comment by christophermaynard** [comment]
Matrix-free 7 point stencil. 

u = A x where H is the helmholtz matrix where 
`U(i,j,k) = Hx(i,jmk) * x(i,j,k) + HW(i,j,k) * x(i-1,j,k)  + HE(i,j,k)*x(i+1,j,k) \\
                                                 + HN(i,j,k) * x(i,j-1,k)   + HS(i,j,k)*x(i,j+1,k) \\
                                                 + HD(i,j,k) * x(i,j,k-1)   + HU(i,j,k)*x(i,j,k+1`

Here, HM=1, HU=HD=-0.485, HE=HW=-1.2e-3 and HN=HS=-2.6e-03

This assumes some things about the size of x which probably aren't true, but equally probably don't matter. In the real code, all the matrix entries are computed and so have different values but here they are all set to the same for convenience of testing the computational performance. What matters is the relative sizes and signs, and the memory accesses so the H's, the values of the non-zero matrix entries have to be arrays even though in our example they are set to the same value. Clear as mud? Happy to elaborate.

**Comment by tkoskela** [comment]
Closing this due to lack of time on both our and Chris's side.
