### ISSUE TITLE
Multiple issues with Sombrero benchmark

### ISSUE THREAD

**Issue by mirenradia** [ukri-excalibur/excalibur-tests#237]
When I do
```
reframe -c /path/to/excalibur-tests/benchmarks/apps/sombrero -l
```
I get the following warning (and no tests are found):
```
WARNING: skipping test file '/path/to/excalibur-tests/benchmarks/apps/sombrero/sombrero.py': module not found error: /path/to/excalibur-tests/benchmarks/apps/sombrero/sombrero.py:10: No module named 'apps'                                                                            
from apps.sombrero import case_filter 
```
Replacing `sombrero.py:L10` with
```python
from benchmarks.apps.sombrero import case_filter
```
resolves this issue but I then get the following warning
```
WARNING: skipping test file '/path/to/excalibur-tests/benchmarks/apps/sombrero/sombrero.py': reframe syntax error: variable 'valid_prog_environs' is declared in more than one of the parent classes of class 'SombreroBuild' (rerun with '-v' for more information)
```
I also have the same problem `SombreroBenchmarkBase`. I believe this is because `SombreroBuild` inherits from both `SpackTest` and `reframe.CompileOnlyRegressionTest` which both in turn inherit from `reframe.RegressionTest` (not sure how diamond inheritance works with Python).

I'm using the following versions
* Python 3.9.12
* ReFrame-HPC 4.4.1

Let me know if any further information would be helpful to debug this.

**Comment by mirenradia** [comment]
Another issue is that for the `ITT-sn` and `ITT-64n` tests, `num_tasks` is set to use all of the cores on a node but this assumes the number of cores per node divides the lattice volume (32x24x24x24) which isn't true on some systems (e.g. the CSD3 Icelakes with 76 cores per node).

**Comment by giordano** [comment]
* The problem `apps.sombrero` vs `benchmarks.apps.sombrero` might have been an overlook when we moved files into the new `benchmarks` subdirectory in #102
* I'll try to look into the inheritance issue
* Yes, these benchmarks should be more flexible and take into account the actual size of the node, or maybe it should at least allow to customise the volume on the command line, not sure there's an easy way to automagically guess a good lattice volume for an arbitrary number of cores
