### ISSUE TITLE
Investigate Streamlit as a possibility for visualisation

### ISSUE THREAD

**Issue by pineapple-cat** [ukri-excalibur/excalibur-tests#259]
Sister issue to #257. Create a simple Streamlit demo to explore how a user may upload a plot config, interact with and change the plot using the front-end, and then download a changed config corresponding to the new plot they created during the session. (Streamlit requires Bokeh v2.4.3, so don't forget to change package requirements.)

**Comment by ilectra** [comment]
I assume you're aware of this already, but I'll just pop it here anyways as I'm cleaning my tabs :grin: : https://discuss.streamlit.io/t/download-upload-session-state/24141
