### ISSUE TITLE
Broken URLs in preview docs

### ISSUE THREAD

**Issue by tkoskela** [ukri-excalibur/excalibur-tests#304]
The URL rewriting in #295 does not seem to work as intended. I get in https://ukri-excalibur.github.io/excalibur-tests/preview/PR299/ url's on the main page that look like `https://ukri-excalibur.github.io/excalibur-tests/preview/PR299/preview/PR299/install/` ie. the `preview/PR299` bit appears twice.

**Comment by giordano** [comment]
I've been looking at the code but struggling to spot what's the error.  This is with PR #294 (before #295): https://github.com/ukri-excalibur/excalibur-tests/blob/35ceb1f2ea66a48f2a861f30febda0d58b80ee25/preview/PR294/index.html#L1212
This is with PR #295:
https://github.com/ukri-excalibur/excalibur-tests/blob/e1c1b1bd2ff7b88b4e32bbb66931f3eec69f64cb/preview/PR295/index.html#L1212
I'm really missing what's causing the duplicate `preview/PRNNN` level.  Ok, time to do some debugging.

**Comment by giordano** [comment]
Ah, wait, it's the second push within the same PR which is messing this up: https://github.com/ukri-excalibur/excalibur-tests/commit/771a2019a9d6fc7626667e460989e4f0e74cdd0e#diff-7fd9bc7707206c4dfa2b00b4bf5684de0c820259a4156c27387ab0f72af9315cR1233.  I'm very confused.
