### ISSUE TITLE
Matrix free hpcg benchmark

### ISSUE THREAD

**Issue by tkoskela** [ukri-excalibur/excalibur-tests#48]

**Comment by dcaseGH** [comment]
A matrix free HPCG has been saved and tagged as version one here:

https://github.com/NCAS-CMS/hpcg_27ptStencil
this has been used in Reframe and Spack - DHC will contact Mose about this. They should work for any version of HPCG.

The next steps are to modify HPCG to solve an 'LFRic problem'.

**Comment by tkoskela** [comment]
After we merge #85 add Spack recipe for this benchmark and create `hpcg` in `apps`

**Comment by dcaseGH** [comment]
There is a branch of the 27pt stencil repository on the NCAS-CMS github for the LFRic problem
https://github.com/NCAS-CMS/hpcg_27ptStencil/tree/lfric_stencil_data

There is a file (dinodump.dat) which is read in, and information attached to the geometry objects etc with data and 'grid' dimensions (check its there - it's from a 24*24*6*30 grid).
The GS preconditioning (with mutligrid) is turned off, although a stencil version of GS could be implemented if wanted.

The HPCG runs tests such as a.A.b - b.A.a to confirm A is symmetric - this fails atm - must convince myself whether this should pass or not and why.

**Comment by dcaseGH** [comment]
I have included 2 tests in the hpcg_benchmarks branch (commit [3bb31c7](https://github.com/ukri-excalibur/excalibur-tests/commit/3bb31c70fb9fc607d28bac54d0f8be88b5e8e76b)), in the apps/hpcg section, with an appropriate spack-environments/repo/packages/hpcg_excalibur/package.py
One, version 1.0 gets a copy of the code to run the 27 pt stencil
The other, version hpcg_lfric gets a copy of a code with a different tag, and makes that for lfric

However, the second part doesn't appear to be installing this version properly, and at the run stage it appears that version 1.0 is run twice, with version hpcg_lfric not run at all. I need to get my wires uncrossed wrt spack next week.

**Comment by dcaseGH** [comment]
Error was giving `version@version` as spack spec, not `spec@version` - fixed at [4dac6f4](https://github.com/ukri-excalibur/excalibur-tests/commit/4dac6f4e06e8c8dcd1869b1f13fa68960d3d256c)

Need vanilla HPCG; refactoring and cleaning reframe/spack; updating hpcg code to have verified outputs etc

**Comment by tkoskela** [comment]
Closing this issue as completed by #157
