### ISSUE TITLE
System configs for all of Tier-2 Isambard system

### ISSUE THREAD

**Issue by tomdeakin** [ukri-excalibur/excalibur-tests#78]
- [x] [XCI - ThunderX2](https://gw4-isambard.github.io/docs/user-guide/XCI.html) (#87)
- [X] [A64FX](https://gw4-isambard.github.io/docs/user-guide/A64FX.html) (#52)
- [x] [MACS](https://gw4-isambard.github.io/docs/user-guide/MACS.html):
    - [X] CascadeLake CPU
    - [X] V100 GPU (#130)
    - [x] Rome CPU (#142)
    - [x] P100 GPU (#143)
    - [x] KNL (#144)
- [x] [Phase 3](https://gw4-isambard.github.io/docs/user-guide/PHASE3.html):
    - [x] A100 GPU (#130)
    - [x] MI50 GPU (#152)
    - [x] Milan CPU (#146)

**Comment by tomdeakin** [comment]
Related to #44

**Comment by tkoskela** [comment]
Need #97 to test AMD GPUs. Others done

**Comment by tkoskela** [comment]
Waiting for Isambard support to update Cray packages to be able to run executables without mpirun

**Comment by kaanolgu** [comment]
> Need #97 to test AMD GPUs. Others done

The commit [83d5571](https://github.com/ukri-excalibur/excalibur-tests/pull/97/commits/83d5571fe6819685928bf639737b7d4d3b992b2d) adds OpenCL implementation which could be used with `backend=amd` option to test ROCM

From the spack package the lines [L307 - L328](https://github.com/spack/spack/blob/4627438373732dff7ce269b1afe5390a9046dd1c/var/spack/repos/builtin/packages/babelstream/package.py#L307C1-L328)  shows which options it require to set 

I think it will be something like ( haven't tested yet)
```
reframe -c benchmarks/apps/babelstream -r --tag ocl --system=AMDGPUMACHINE? -S build_locally=false -S spack_spec='babelstream@develop +ocl backend=amd'
```

**Comment by giordano** [comment]
I believe this is complete now, with the caveat that on the Phase 3 partition MPI programs using autoconf may not be configured correctly for the time being: https://github.com/ukri-excalibur/excalibur-tests/pull/152#issuecomment-1551139575.  Some settings can probably be tweaked, but the basic configuration for all partitions should now be available, so this issue can be closed.
