### ISSUE TITLE
Investigate Excalibur testbeds and add system configs to reframe where relevant 

### ISSUE THREAD

**Issue by christophermaynard** [ukri-excalibur/excalibur-tests#84]

**Comment by tkoskela** [comment]
- [ ] Read Martin's brochure, make first guess of which testbeds are relevant for us

**Comment by tkoskela** [comment]
# Completed Projects
- [ ] Adaptable Cluster Project
- [ ] AMD GPU
- [ ] Storage and RAM as a service
- [ ] ARM+GPU Demonstrator
- [ ] Cerebras Wafer Scale Engine
- [ ] Graphcore
- [ ] FPGA
- [ ] NextSilicon
# Current Projects
- [ ] Exascale Data
- [ ] RISC-V
- [ ] Rockport
# Upcoming Projects
- [ ] Coarse Grained Reconfigurable Architectures
- [ ] DWAVE Quantum Computing
- [ ] CXL Technology Demonstrator

**Comment by tkoskela** [comment]
Waiting for #97 to test the Durham testbeds
