### ISSUE TITLE
Consider moving to ReFrame v4

### ISSUE THREAD

**Issue by giordano** [ukri-excalibur/excalibur-tests#89]

**Comment by ilectra** [comment]
We need to bump this up. Many of the changes to v4 affect the way the perflogs are named and formatted, so it will affect directly the post-processing scripts. Someone was telling me recently (Tom Meyer from Leicester? Kacper from Cambridge? Ugh, can't remember!) that they did move to v4 in their local fork, and it wasn't so terrible. Well, the changes needed to the framework weren't so terrible. Changes (small, I assume) to the individual benchmarks still have to be propagated.

**Comment by giordano** [comment]
Yeah, I don't expect we need to change *too* much, we just need to decide whether to move to the newer version.

**Comment by ilectra** [comment]
We do want to move to the newer version. It will have to happen sooner or later, so we better do it sooner to avoid breaking things later.

**Comment by ilectra** [comment]
Things that I've randomly collected that have to change with v4:
- New [tests' naming scheme](https://reframe-hpc.readthedocs.io/en/stable/manpage.html#test-naming-scheme) will affect perflog file name and conditions for which a new perflog file is created, but I don't think it affects existing stuff.
- The [formatting of perfvars](https://reframe-hpc.readthedocs.io/en/stable/config_reference.html#config.logging.handlers_perflog.format_perfvars)
- Environment variables `check_variables` dictionary in the [logging.handlers_perflog.format](https://reframe-hpc.readthedocs.io/en/stable/config_reference.html#config.logging.handlers_perflog.format) changes to `check_env_vars`

**Comment by giordano** [comment]
For reference: https://reframe-hpc.readthedocs.io/en/stable/whats_new_40.html

**Comment by tomdeakin** [comment]
My 2c: keeping up with the latest versions of the tools in the framework is only a good thing.
